// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaLeWMTNbpRNGcaIg8KySOoJoDMnsBSY8',
    appId: '1:343236929657:web:cae69b981f10f4392fcca8',
    messagingSenderId: '343236929657',
    projectId: 'destinasi-wisata-7b1ed',
    authDomain: 'destinasi-wisata-7b1ed.firebaseapp.com',
    storageBucket: 'destinasi-wisata-7b1ed.firebasestorage.app',
    measurementId: 'G-H9SC09CVVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Jg3VL6rgEfvghExwpS1RFLX1j1dPmoM',
    appId: '1:343236929657:android:4048434b9bed00b32fcca8',
    messagingSenderId: '343236929657',
    projectId: 'destinasi-wisata-7b1ed',
    storageBucket: 'destinasi-wisata-7b1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRE41m9ftmyJKvo_ImC6o2TNVn22x18BE',
    appId: '1:343236929657:ios:47ee17084c6c89222fcca8',
    messagingSenderId: '343236929657',
    projectId: 'destinasi-wisata-7b1ed',
    storageBucket: 'destinasi-wisata-7b1ed.firebasestorage.app',
    iosBundleId: 'com.example.prototypeAppDestinasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRE41m9ftmyJKvo_ImC6o2TNVn22x18BE',
    appId: '1:343236929657:ios:47ee17084c6c89222fcca8',
    messagingSenderId: '343236929657',
    projectId: 'destinasi-wisata-7b1ed',
    storageBucket: 'destinasi-wisata-7b1ed.firebasestorage.app',
    iosBundleId: 'com.example.prototypeAppDestinasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaLeWMTNbpRNGcaIg8KySOoJoDMnsBSY8',
    appId: '1:343236929657:web:5a34532e27a240d32fcca8',
    messagingSenderId: '343236929657',
    projectId: 'destinasi-wisata-7b1ed',
    authDomain: 'destinasi-wisata-7b1ed.firebaseapp.com',
    storageBucket: 'destinasi-wisata-7b1ed.firebasestorage.app',
    measurementId: 'G-TMPTCMPVKM',
  );
}
